before_commands:
  - 'composer install --no-interaction'

filter:
  excluded_paths:
    - bin/*
    - src/CL/SlackCli/Resources/*
    - src/CL/SlackCli/Tests/*
    - vendor/*

tools:
  external_code_coverage:
    timeout: 600
  php_analyzer: true
  php_code_sniffer:
    config:
      ruleset: config/ruleset.xml
  php_cs_fixer: true
  php_loc: true
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true
  php_cs_fixer:
    config:
      level: symfony
