before_commands:
  - 'composer install --no-interaction'

filter:
  paths:
    - src/*
  excluded_paths:
    - src/CL/SlackCli/Resources/*
    - src/CL/SlackCli/Tests/*

tools:
  external_code_coverage:
    timeout: 600
  php_analyzer: true
  php_code_sniffer: true
  php_cs_fixer: true
  php_loc: true
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true
  php_cs_fixer:
    config:
      level: symfony
